package pl.infoshare.workandfun.announcements.announcement_repo.entity.additionals;

public enum ServiceType {
    GLOWNA_KATEGORIA("Głowna kategoria",0),
    BUDOWA_DOMU("Budowa domu",1),
    ELEKTRYK( "Elektryk",1),
    HYDRAULIK( "Hydraulik",1),
    MALARZ( "Malarz",1),
    MEBLE_I_ZABUDOWA( "Meble i zabudowa",1),
    MOTORYZACJA("Motoryzacja",1),
    OGROD("Ogród",1),
    ORGANIZACJA_IMPREZ( "Organizacja imprez",1),
    PROJEKTOWANIE( "Projektowanie",1),
    REMONT("Remont",1),
    SPRZATANIE( "Sprzątanie",1),
    SZKOLENIA_I_JEZYKI_OBCE( "Szkolenia i języki obce",1),
    TRANSPORT("Transport",1),
    USLUGI_DLA_BIZNESU( "Usługi dla biznesu",1),
    MONTAZ_I_NAPRAWA("Montaż i naprawa",1),
    USLUGI_FINANSOWE( "Usługi finansowe",1),
    USLUGI_PRAWNE_I_ADMINISTRACYJNE( "Usługi prawne i administracyjne",1),
    USLUGI_ZDALNE("Usługi zdalne",1),
    ZDROWIE_I_URODA("Zdrowie i uroda",1),
    ZLOTA_RACZKA( "Złota rączka",1),
    INNE("Inne",1),

    BUDOWA_DOMU_BUDOWA_OD_PODSTAW( "Budowa od podstaw",2),
    BUDOWA_DOMU_DACH_I_ELEWACJA( "Dach i elewacja",2),
    BUDOWA_DOMU_GARAZE_I_BRAMY( "Garaże i bramy",2),
    BUDOWA_DOMU_INSTALACJE("Na zewnątrz",2),
    BUDOWA_DOMU_PODLOGI("Podlogi",2),
    BUDOWA_DOMU_SCIANY_I_SUFIT("Ściany i sufit",2),
    BUDOWA_DOMU_POZOSTALE("Pozostałe",2),
    HYDRAULIK_INSTALACJA_CENTRALNEGO_OGRZEWANIA( "Instalacja centralnego ogrzewania",2),
    HYDRAULIK_INSTALACJA_GAZOWA("Instalacja gazowa",2),
    HYDRAULIK_MONTAZ_WANNY("Montaż wanny",2),
    HYDRAULIK_MONTAZ_WC("Montaż wc",2),
    HYDRAULIK_OGRZEWANIE_PODLOGOWE_ELEKTRYCZNE( "Ogrzewanie podlogowe elektryczne",2),
    HYDRAULIK_UDRAZNIANIE_RUR("Udrażnianie rur",2),
    HYDRAULIK_POZOSTALE_USLUGI_HYDRAULICZNE("Pozostale usługi hydrauliczne",2),
    HYDRAULIK_POZOSTALE("Pozostałe",2),
    MEBLE_I_ZABUDOWA_NAPRAWA_MEBLI( "Naprawa mebli", 2),
    MEBLE_I_ZABUDOWA_LUSTRA_NA_WYMIAR("Lustra na wymiar", 2),
    MEBLE_I_ZABUDOWA_MALOWANIE_MEBLI("Malowanie mebli", 2),
    MEBLE_I_ZABUDOWA_MEBLE_KUCHENNE_NA_WYMIAR("Meble kuchenne na wymiar", 2),
    MEBLE_I_ZABUDOWA_MEBLE_NA_WYMIAR( "Meble na wymiar", 2),
    MEBLE_I_ZABUDOWA_MEBLE_LAZIENKOWE_NA_WYMIAR( "Meble łazienkowe na wymiar", 2),
    MEBLE_I_ZABUDOWA_OKLEJANIE_MEBLI("Oklejanie mebli", 2),
    MEBLE_I_ZABUDOWA_STOLARZ("Stolarz", 2),
    MEBLE_I_ZABUDOWA_SZKLARZ("Szklarz", 2),
    MEBLE_I_ZABUDOWA_POZOSTALE( "Pozostałe", 2),
    MOTORYZACJA_BLACHARZ_SAMOCHODOWY("Blacharz samochodowy", 2),
    MOTORYZACJA_GEOMETRIA_KOL("Geometria kół", 2),
    MOTORYZACJA_INSTALACJA_LPG( "Instalacja lpg", 2),
    MOTORYZACJA_LAKIERNIK("Lakiernik", 2),
    MOTORYZACJA_MECHANIK_MOTOCYKLOWY("Mechanik motocyklowy", 2),
    MOTORYZACJA_NAPRAWA_SZYB_SAMOCHODOWYCH( "Naprawa szyb samochodowych", 2),
    MOTORYZACJA_NAUKA_JAZDY( "Nauka jazdy", 2),
    MOTORYZACJA_PRZYCIEMNIANIE_SZYB( "Przyciemnianie szyb", 2),
    MOTORYZACJA_SERWIS_INSTALACJI_LPG("Serwis instalacji lpg", 2),
    MOTORYZACJA_SPAWACZ( "Spawacz", 2),
    MOTORYZACJA_TAPICER_SAMOCHODOWY( "Tapicer samochodowy", 2),
    MOTORYZACJA_TUNING_SAMOCHODOW( "Tuning samochodów", 2),
    MOTORYZACJA_WULKANIZACJA_OPON( "Wulkanizacja opon", 2),
    MOTORYZACJA_WYMIANA_OLEJU("Wymiana oleju", 2),
    MOTORYZACJA_WYMIANA_SPRZEGLA( "Wymiana sprzęgła", 2),
    MOTORYZACJA_POZOSTALE("Pozostałe", 2),
    SZKOLENIA_I_JEZYKI_OBCE_NAUKA_JAZDY( "Nauka jazdy", 2),
    SZKOLENIA_I_JEZYKI_OBCE_NAUKA_JEZYKOW( "Nauka języków", 2),
    SZKOLENIA_I_JEZYKI_OBCE_SZKOLENIA_PRZECIWPOZAROWE( "Szkolenia przeciwpożarowe", 2),
    SZKOLENIA_I_JEZYKI_OBCE_SZKOLENIA_Z_PIERWSZEJ_POMOCY( "Szkolenia z pierwszej pomocy", 2),
    SZKOLENIA_I_JEZYKI_OBCE_SZKOLA_JEZYKOWA( "Szkoła językowa", 2),
    SZKOLENIA_I_JEZYKI_OBCE_TLUMACZENIE_PRZYSIEGLE( "Tłumaczenie przysięgłe", 2),
    SZKOLENIA_I_JEZYKI_OBCE_TLUMACZENIE_STRON_INTERNETOWYCH("Tłumaczenie stron internetowych", 2),
    TRANSPORT_AUTO_DO_SLUBU("Auto do ślubu", 2),
    TRANSPORT_PRZEPROWADZKI( "Przeprowadzki", 2),
    TRANSPORT_SPEDYCJA( "Spedycja", 2),
    TRANSPORT_TRANSPORT_SAMOCHODOW_KRAJOWY( "Transport samochodów krajowy", 2),
    TRANSPORT_TRANSPORT_SAMOCHODOW_ZAGRANICZNY( "Transport samochodów zagraniczny", 2),
    TRANSPORT_TRANSPORT_ZAGRANICZNY( "Transport zagraniczny", 2),
    TRANSPORT_WYNAJEM_AUTOKAROW( "Wynajem autokarów", 2),
    TRANSPORT_WYNAJEM_BUSOW( "Wynajem busów", 2),
    TRANSPORT_WYNAJEM_LIMUZYNY("Wynajem limuzyny", 2),
    TRANSPORT_ZARZADZANIE_FLOTA( "Zarządzanie flotą", 2),
    REMONT_BALUSTRADY_I_PORECZE( "Balustrady i poręcze", 2),
    REMONT_DACH_I_ELEWACJA("Dach i elewacja", 2),
    REMONT_INSTALACJE("Instalacje", 2),
    REMONT_INTELIGENTNY_DOM( "Inteligentny dom", 2),
    REMONT_PODLOGI("Podłogi", 2),
    REMONT_REMONTY_BUDYNKOW("Remonty budynków", 2),
    REMONT_USLUGI_MALARSKIE( "Usługi malarskie", 2),
    REMONT_WYKONCZENIE_WNETRZ( "Wykończenie wnętrz", 2),
    REMONT_SCIANY_I_SUFIT("Ściany i sufit", 2),
    REMONT_POZOSTALE( "Pozostałe", 2);

    private final String serviceTypeName;
    private final int level;

    ServiceType(String serviceTypeName, int level) {
        this.serviceTypeName = serviceTypeName;
        this.level = level;
    }

    public String getServiceTypeName() {
        return serviceTypeName;
    }
}

