insert into announcement (a_id, a_type, a_header, a_service_type, a_city, a_city_district, a_unit, a_price
                         , owner_user_id, a_voivodeship, a_date, a_name_of_advertiser, a_email, a_is_price_negotiable, a_description
                         , a_phone_number, a_price_addition_comment)
values ('1', 'SERVICE_OFFER', 'Diagnostyka i serwis aut elektrycznych', 'MOTORYZACJA', 'Legnica', '', '', 'do ustalenia indywidualnie', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', true, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('2', 'SERVICE_OFFER', 'Diagnostyka i serwis aut elektrycznych', 'MOTORYZACJA', 'Legnica', '', '', 'do ustalenia indywidualnie', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', true, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('3', 'SERVICE_OFFER', 'Pomagam przy remoncie', 'REMONT_POZOSTALE', 'Lublin', '', '', 'do ustalenia indywidualnie', null, 'LUBELSKIE', '2022-02-25 12:51:55', 'Leszek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('4', 'SERVICE_OFFER', 'Pomagam przy remoncie', 'REMONT_POZOSTALE', 'Lublin', '', '', 'do ustalenia indywidualnie', null, 'LUBELSKIE', '2022-02-25 12:51:55', 'Romek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('5', 'SERVICE_OFFER', 'Pomagam przy remoncie', 'REMONT_POZOSTALE', 'Lublin', '', '', 'do ustalenia indywidualnie', null, 'LUBELSKIE', '2022-02-25 12:51:55', 'Romek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('6', 'SERVICE_DEMAND', 'Potrzebuje bus', 'MOTORYZACJA', 'Legnica', '', '', '150', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', false, 'Potrzebuję bus do przeprowadzki', '+48654789321', ''),
       ('7', 'SERVICE_DEMAND', 'Potrzebuje bus', 'MOTORYZACJA', 'Legnica', '', '', '100', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', true, 'Potrzebuję bus do przeprowadzki', '+48147963258', ''),
       ('8', 'SERVICE_DEMAND', 'Potrzebuje bus', 'MOTORYZACJA', 'Legnica', '', '', '120', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', 'cena za godzinę'),
       ('9', 'SERVICE_DEMAND', 'Potrzebuje bus', 'MOTORYZACJA', 'Legnica', '', '', 'do ustalenia indywidualnie', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('10', 'SERVICE_DEMAND', 'Potrzebuje bus', 'MOTORYZACJA', 'Legnica', '', '', 'do ustalenia indywidualnie', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('11', 'SERVICE_OFFER', 'Diagnostyka i serwis aut elektrycznych', 'MOTORYZACJA', 'Legnica', '', '', 'do ustalenia indywidualnie', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('12', 'SERVICE_OFFER', 'Diagnostyka i serwis aut elektrycznych', 'MOTORYZACJA', 'Legnica', '', '', 'do ustalenia indywidualnie', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('13', 'SERVICE_OFFER', 'Pomagam przy remoncie', 'REMONT_POZOSTALE', 'Lublin', '', '', 'do ustalenia indywidualnie', null, 'LUBELSKIE', '2022-02-25 12:51:55', 'Leszek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('14', 'SERVICE_OFFER', 'Pomagam przy remoncie', 'REMONT_POZOSTALE', 'Lublin', '', '', 'do ustalenia indywidualnie', null, 'LUBELSKIE', '2022-02-25 12:51:55', 'Romek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('15', 'SERVICE_OFFER', 'Pomagam przy remoncie', 'REMONT_POZOSTALE', 'Lublin', '', '', 'do ustalenia indywidualnie', null, 'LUBELSKIE', '2022-02-25 12:51:55', 'Romek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('16', 'SERVICE_DEMAND', 'Potrzebuje bus', 'MOTORYZACJA', 'Legnica', '', '', '150', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', false, 'Potrzebuję bus do przeprowadzki', '+48654789321', ''),
       ('17', 'SERVICE_DEMAND', 'Potrzebuje bus', 'MOTORYZACJA', 'Legnica', '', '', '100', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', true, 'Potrzebuję bus do przeprowadzki', '+48147963258', ''),
       ('18', 'SERVICE_DEMAND', 'Potrzebuje bus', 'MOTORYZACJA', 'Legnica', '', '', '120', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', 'cena za godzinę'),
       ('19', 'SERVICE_DEMAND', 'Potrzebuje bus', 'MOTORYZACJA', 'Legnica', '', '', 'do ustalenia indywidualnie', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', ''),
       ('20', 'SERVICE_DEMAND', 'Potrzebuje bus', 'MOTORYZACJA', 'Legnica', '', '', 'do ustalenia indywidualnie', null, 'DOLNOSLASKIE', '2022-02-26 23:51:37', 'Leszek', 'rexoAuto@gmail.com', false, 'Diagnostyka i serwis aut elektrycznych. Pomagam przy zakupie auta elektrycznego', '+48741741741', '');